cmake_minimum_required(VERSION 3.20.0)
find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(k380_low_power)

target_sources(app PRIVATE ../../src/low_power.c)
if(CONFIG_K380_AUTO_SYSTEM_OFF)
  target_sources(app PRIVATE src/main.c)
else()
  target_sources(app PRIVATE src/gate.c)
endif()
target_include_directories(app PRIVATE ../../include)
target_compile_definitions(app PRIVATE CONFIG_K380_LOW_POWER_TEST=1)
