"""Generate a deterministic C header from the reviewed macro VM JSON fixture."""

from __future__ import annotations

import argparse
import json
import re
import struct
from pathlib import Path


def _literal(data: bytes) -> str:
    values = ", ".join(f"0x{value:02x}" for value in data)
    return values or "0"


def generate(input_path: Path, output_path: Path) -> None:
    document = json.loads(input_path.read_text(encoding="utf-8"))
    vectors = document.get("vectors")
    if document.get("format") != "k380-macro-vm-v1" or not isinstance(vectors, list):
        raise ValueError("invalid macro VM vector document")

    declarations: list[str] = []
    entries: list[str] = []
    for vector in vectors:
        name = vector["name"]
        if not isinstance(name, str) or re.fullmatch(r"[a-z0-9-]+", name) is None:
            raise ValueError(f"invalid vector name: {name!r}")
        package = bytes.fromhex(vector["package_hex"])
        code = bytes.fromhex(vector["code_hex"])
        expected_crc = int(vector["package_crc32"], 16)
        if len(package) < 16 or package[12:16] != struct.pack("<I", expected_crc):
            raise ValueError(f"reviewed CRC mismatch in vector {name}")
        function_count = package[6]
        code_length = struct.unpack_from("<H", package, 8)[0]
        code_offset = 16 + function_count * 4
        if package[code_offset:] != code or len(code) != code_length:
            raise ValueError(f"reviewed code mismatch in vector {name}")
        identifier = re.sub(r"[^a-z0-9]", "_", name)
        array_name = f"k380_macro_vm_{identifier}_package"
        declarations.append(
            f"static const uint8_t {array_name}[] = {{ {_literal(package)} }};\n"
            f"#define K380_MACRO_VM_{identifier.upper()}_PACKAGE_LEN {len(package)}U\n"
        )
        source = json.dumps(vector["source"], ensure_ascii=False)
        entries.append(
            f'    {{ "{name}", {source}, {array_name}, '
            f"K380_MACRO_VM_{identifier.upper()}_PACKAGE_LEN }},"
        )

    content = """/* Generated by generate_macro_vm_header.py. Do not edit. */
#ifndef K380_MACRO_VM_VECTORS_H_
#define K380_MACRO_VM_VECTORS_H_

#include <stddef.h>
#include <stdint.h>

struct k380_macro_vm_test_vector {
    const char *name;
    const char *source;
    const uint8_t *package;
    size_t package_len;
};

""" + "\n".join(declarations) + "\nstatic const struct k380_macro_vm_test_vector k380_macro_vm_vectors[] = {\n" + "\n".join(entries) + "\n};\n\n#define K380_MACRO_VM_VECTOR_COUNT (sizeof(k380_macro_vm_vectors) / sizeof(k380_macro_vm_vectors[0]))\n\n#endif\n"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    generate(args.input, args.output)


if __name__ == "__main__":
    main()
