/* Generated by generate_macro_vm_header.py. Do not edit. */
#ifndef K380_MACRO_VM_VECTORS_H_
#define K380_MACRO_VM_VECTORS_H_

#include <stddef.h>
#include <stdint.h>

struct k380_macro_vm_test_vector {
    const char *name;
    const char *source;
    const uint8_t *package;
    size_t package_len;
};

static const uint8_t k380_macro_vm_wait_600000_package[] = { 0x4b, 0x56, 0x4d, 0x31, 0x01, 0x00, 0x00, 0x00, 0x0c, 0x00, 0x00, 0x00, 0x61, 0x55, 0x24, 0x9c, 0x01, 0x04, 0x00, 0x10, 0xc0, 0x27, 0x09, 0x00, 0x02, 0x04, 0x00, 0x00 };
#define K380_MACRO_VM_WAIT_600000_PACKAGE_LEN 28U

static const struct k380_macro_vm_test_vector k380_macro_vm_vectors[] = {
    { "wait-600000", "按下 A\n等待 600000\n弹起 A\n", k380_macro_vm_wait_600000_package, K380_MACRO_VM_WAIT_600000_PACKAGE_LEN },
};

#define K380_MACRO_VM_VECTOR_COUNT (sizeof(k380_macro_vm_vectors) / sizeof(k380_macro_vm_vectors[0]))

#endif
