zephyr_include_directories(include)
if(CONFIG_K380_STATUS_INDICATOR)
  target_sources(app PRIVATE src/status_indicator.c)
endif()
if(CONFIG_K380_BLE_SLOT_POLICY)
  target_sources(app PRIVATE src/ble_slot_policy.c)
endif()
if(CONFIG_K380_BATTERY_POLICY)
  target_sources(app PRIVATE src/battery_policy.c)
endif()
if(CONFIG_K380_SOFT_OFF)
  target_sources(app PRIVATE src/soft_off.c)
endif()
add_subdirectory(drivers/kscan)
